services:
  web:
    build:
      context: ./
      target: mt-stats-web
    restart: always
    ports: 
      - "3123:3000" # change 3123 to another port if needed 
    depends_on:
      - db
    environment:
      POSTGRES_ADDRESS: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mt
  
  srv:
    build:
      context: ./
      target: mt-stats-srv
    restart: always
    depends_on:
      - db
      - mqtt
    environment:
      POSTGRES_ADDRESS: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mt
      MQTT_ADDRESS: mqtt://mqtt
      MQTT_CLIENTID: mt-stats

  db:
    image: postgres:16
    restart: always
    ports:
      - "5444:5432" # optional - allows direct connection to db with something like pgadmin
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mt
    volumes:
      - ./assets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
  mqtt:
    image: "eclipse-mosquitto:2"
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./assets/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
volumes:
  db_data:
  mqtt_data:
  mqtt_log: